[workspace]
members = ["programs/nft-staking"]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "./devnet-wallet.json"

[programs.mainnet]
nft_staking = "C739MJdnbYBJ7TkJpVe75Y3ddhV3Ya9R5V1o6KzVqtzB"

[scripts]
test = "ts-mocha --path tsconfig.json -t 1000000 tests/nft-staking/*.ts"
